name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: peaceiris/actions-export-envs@v1.1.0
        id: envs

      - run: echo "$ACTIONS_CACHE_URL"
        env:
          ACTIONS_CACHE_URL: ${{ steps.envs.outputs.ACTIONS_CACHE_URL }}

      - run: echo "$ACTIONS_RUNTIME_TOKEN"
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ steps.envs.outputs.ACTIONS_RUNTIME_TOKEN }}
